commerce_currency_resolver.settings:
  type: config_object
  label: 'Commerce currency resolvers settings'
  mapping:
    currency_mapping:
      type: string
      label: 'Currency mapping'
    currency_geo:
      type: string
      label: 'Location modules'
    currency_source:
      type: string
      label: 'Currency source'
    currency_default:
      type: string
      label: 'Currency default'

commerce_currency_resolver.currency_conversion:
  type: config_object
  label: 'Currency conversion'
  mapping:
    source:
      type: string
      label: 'Currency exchange service'
    api_key:
      type: string
      label: 'API key'
    cron:
      type: integer
      label: 'Exchange rate cron'
    use_cross_sync:
      type: integer
      label: 'Use cross conversion between non default currencies'
    demo_amount:
      type: string
      label: 'Demo amount'
    exchange:
      type: sequence
      label: 'Exchange rates'
      sequence:
        type: sequence
        label: 'Currency upon exchanges is based'
        sequence:
          type: sequence
          label: 'Other currencies exchange rates'
          value:
            type: string
            label: 'Value'
          sync:
            type: string
            label: 'Sync'

commerce_currency_resolver.currency_mapping:
  type: config_object
  label: 'Currency mapping'
  mapping:
    domicile_currency:
      type: string
      label: 'Use domicile currency per country'
    logic:
      type: string
      label: 'Matrix logic'
    matrix:
      type: sequence
      label: 'Matrix'
      sequence:
        type: string

commerce_currency_resolver.commerce_condition.plugin.order_total_price_currency:
  type: commerce_condition_configuration
  mapping:
    operator:
      type: string
      label: 'Operator'
    amount:
      type: field.value.commerce_price
      label: 'Amount'
    autocalculate:
      type: integer
      label: 'Autocalculate'
    fields:
      type: sequence
      label: 'Fields'
      sequence:
        type: field.value.commerce_price
        label: 'Amount'
